name: Metric logging with wandb

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@master
        id: cache
        with:
          path: ${{ env.pythonLocation}}/lib/python3.7/site-packages/*
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
          run: |
            echo ${env.pythonLocation}
            
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "Installing dependencies and caching them."
          pip install -r requirements.txt
     
      - name: show module
        run: pip show pandas
      
      - name: Train model and log wandb metric
        run: |
          # Your ML workflow goes here
          python train.py --key ${{ secrets.WANDB_API_KEY }}
          echo "Finished run."
          cat metrics.txt >> report.md
          cml-send-comment report.md
      - name: Archive metrics
        uses: actions/upload-artifact@v2
        with:
          name: metrics csv file
          path: metrics.csv
